# ============================================================================
# Groundwater Risk Assessment Workflow Settings
# ============================================================================
#
# This file contains user-configurable settings for the standardized workflow.
# Modify these values to adjust risk thresholds and workflow behavior.
#
# WARNING: Changing these settings will affect risk assessment results.
# Document any changes for reproducibility.

# -------------------------------------------------------------------
# Risk Assessment Thresholds
# -------------------------------------------------------------------

# General assessment: Universal distance threshold (meters)
# Sites within this distance are flagged in Step 5a
risk_threshold_m: 500

# Multi-threshold analysis: Additional thresholds to test (optional)
# Set enable_multi_threshold_analysis to true to run sensitivity analysis
additional_thresholds_m:
  - 250
  - 500
  - 1000
  - 1500
  - 2000

enable_multi_threshold_analysis: false

# -------------------------------------------------------------------
# Workflow Filters
# -------------------------------------------------------------------

# River contact filter: Value indicating groundwater-surface water interaction
# Only river segments with this Kontakt value are considered
contact_filter_value: 1

# -------------------------------------------------------------------
# Progress Reporting
# -------------------------------------------------------------------

# How often to print progress updates during long operations (percentage)
progress_interval_percent: 10

# -------------------------------------------------------------------
# Notes on Compound-Specific Thresholds
# -------------------------------------------------------------------
#
# Compound-specific thresholds for Step 5b are defined in:
#   risikovurdering/refined_compound_analysis.py
#
# These are based on literature (see LITERATURE_COMPOUND_MAPPING)
# and should NOT be changed without scientific justification.
#
# Examples:
#   - BTXER (benzene, oil products): 50m
#   - Chlorinated solvents: 500m
#   - PAH compounds: 30m
#   - Pesticides: 500m
#
# To modify these, edit refined_compound_analysis.py with proper documentation.
